# Generated by Django 3.2.9 on 2021-12-26 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iam_admin', '0002_auto_20211226_0806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='block',
            new_name='userblock',
        ),
    ]
