# Generated by Django 3.2.9 on 2021-12-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam_admin', '0003_rename_block_userblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userblock',
        ),
    ]
